/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.restaurantedonrigo;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class Cocina extends javax.swing.JFrame {
    
    //Declaro el modelo de la tabla Ordenes
    private DefaultTableModel productosModel;
    //Declaro el array que almacena el titulo de la tabla
    private String[] tituloProductos;

    /**
     * Creates new form Cocina
     */
    public Cocina() {
        setTitle("Cocina");
        
        initComponents();
        
        //centro la ventana
        setLocationRelativeTo(null);
        
        //Transparencia Btn
        transparenciaBtn();
        //EleminarBordes
        eliminarBordeBtn();
        
        //Tabla menu
        productosModel = new DefaultTableModel();
        tituloProductos = new String[]{"Nombre", "Precio", "Categoria","Mesa"};
        //Agragamos el titulo a la tabla
        productosModel.setColumnIdentifiers(tituloProductos);
        tblProductos.setModel(productosModel);
    }
    
    public void transparenciaBtn()
    {
        //Transparencia a los botones
        btnMenu.setBackground(new Color(255,255,255));
        btnInicio.setBackground(new Color(255,255,255));        
    }
    
    public void eliminarBordeBtn()
    {
        btnMenu.setFocusPainted(false);
        btnCocina.setFocusPainted(false);
        btnInicio.setFocusPainted(false);
        btnSalir.setFocusPainted(false);
        btnEliminarFila.setFocusPainted(false);     
    }
    
    public void recibirArrayOrdenes(ArrayList<Orden> listaOrdenActual, String mesa)
    {
        configurarTabla(listaOrdenActual, mesa);
    }
    
    public void configurarTabla(ArrayList<Orden> listaOrdenActual, String mesa)
    {
        // Agrega filas a la tabla usando los datos del ArrayList
        for (Orden dato : listaOrdenActual) {
            Object[] fila = new Object[4];
            fila[0] = dato.getNombre();
            fila[1] = dato.getPrecio();
            fila[2] = dato.getCategoria();
            fila[3] = mesa;
            productosModel.addRow(fila);
        }

        // Crea la tabla con el modelo configurado
        tblProductos.setModel(productosModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_nav_white = new javax.swing.JPanel();
        tittle_dr = new javax.swing.JLabel();
        btnCocina = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        lblCocina = new javax.swing.JLabel();
        btnEliminarFila = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg_nav_white.setBackground(new java.awt.Color(255, 255, 255));
        bg_nav_white.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tittle_dr.setFont(new java.awt.Font("Montserrat Medium", 1, 14)); // NOI18N
        tittle_dr.setText("DR");
        bg_nav_white.add(tittle_dr, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 30, 30));

        btnCocina.setBackground(new java.awt.Color(104, 159, 56));
        btnCocina.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnCocina.setForeground(new java.awt.Color(255, 255, 255));
        btnCocina.setText("COCINA");
        btnCocina.setAlignmentY(0.0F);
        btnCocina.setBorder(null);
        btnCocina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCocinaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCocinaMouseExited(evt);
            }
        });
        btnCocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocinaActionPerformed(evt);
            }
        });
        bg_nav_white.add(btnCocina, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 103, 70, 50));

        btnInicio.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(132, 132, 132));
        btnInicio.setText("INICIO");
        btnInicio.setBorder(null);
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInicioMouseExited(evt);
            }
        });
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        bg_nav_white.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 153, 70, 50));

        btnMenu.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(132, 132, 132));
        btnMenu.setText("MENU");
        btnMenu.setBorder(null);
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuMouseExited(evt);
            }
        });
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        bg_nav_white.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 53, 70, 50));

        btnSalir.setBackground(new java.awt.Color(211, 47, 47));
        btnSalir.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.setBorder(null);
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        bg_nav_white.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 70, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        lblCocina.setFont(new java.awt.Font("Montserrat Medium", 1, 14)); // NOI18N
        lblCocina.setText("Cocina");

        btnEliminarFila.setBackground(new java.awt.Color(211, 47, 47));
        btnEliminarFila.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnEliminarFila.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarFila.setText("ELIMINAR");
        btnEliminarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFilaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarFila, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCocina)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblCocina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarFila, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg_nav_white, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_nav_white, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCocinaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCocinaMouseEntered
        //Activo
    }//GEN-LAST:event_btnCocinaMouseEntered

    private void btnCocinaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCocinaMouseExited
        //Activo
    }//GEN-LAST:event_btnCocinaMouseExited

    private void btnCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocinaActionPerformed
        //Activo
    }//GEN-LAST:event_btnCocinaActionPerformed

    private void btnInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseEntered
        btnInicio.setBackground(new Color(215,215,215));
    }//GEN-LAST:event_btnInicioMouseEntered

    private void btnInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseExited
        btnInicio.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnInicioMouseExited

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        //ocultamos ventana Inicio
        setVisible(false);
        //costramos ventana Mesero
        new Inicio().setVisible(true);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        btnSalir.setBackground(new Color(200,46,46));
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        btnSalir.setBackground(new Color(211,47,47));
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseEntered
        btnMenu.setBackground(new Color(215,215,215));
    }//GEN-LAST:event_btnMenuMouseEntered

    private void btnMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseExited
        btnMenu.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnMenuMouseExited

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        //ocultamos ventana Inicio
        setVisible(false);
        //costramos ventana Mesero
        new Mesero().setVisible(true);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnEliminarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFilaActionPerformed
        //guardamos la fila seleccionada y la eliminamos de la tabla
        int fila = tblProductos.getSelectedRow();
        
        if (fila != -1) 
        {
            DefaultTableModel model = (DefaultTableModel) tblProductos.getModel();
            model.removeRow(fila);
            tblProductos.setModel(model);
        }
    }//GEN-LAST:event_btnEliminarFilaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cocina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_nav_white;
    private javax.swing.JButton btnCocina;
    private javax.swing.JButton btnEliminarFila;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCocina;
    private javax.swing.JTable tblProductos;
    private javax.swing.JLabel tittle_dr;
    // End of variables declaration//GEN-END:variables
}
