/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.restaurantedonrigo;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public final class Mesero extends javax.swing.JFrame {
    
    //Declaro el modelo de la tabla que almacena los datos
    private DefaultTableModel menuModel;
    //Declaro el modelo de la tabla Ordenes
    private DefaultTableModel ordenesModel;
    //Declaro el array que almacena el titulo de la tabla
    private String[] tituloProductos;
    //titulo de las ordenes
    private String[] tituloOrdenes;
    //Arrays list
    private ArrayList<Producto> listaProductos = new ArrayList<>();
    //Array Ordenes
    private ArrayList<Orden> listaOrdenActual = new ArrayList<>();
        
    /**
     * Creates new form Mesero
     */
    public Mesero() {
        setTitle("Mesero");
        
        initComponents();
                
        //centro la ventana
        setLocationRelativeTo(null);
        
        // Evita que se pueda modificar el tamaño del JFrame
        setResizable(false);
        
         // Establece el tamaño del JFrame
        setSize(860, 576);
        
        //transparencia Botones Menu
        transparenciaBtn();
        
        //Quitar borde Bototnes
        eliminarBordeBtn();
        
        //Tabla menu
        menuModel = new DefaultTableModel();
        tituloProductos = new String[]{"Nombre", "Precio", "Categoria"};
        //Agragamos el titulo a la tabla
        menuModel.setColumnIdentifiers(tituloProductos);
        tblMenu.setModel(menuModel);
        
        //Tabla Ordenes
        ordenesModel = new DefaultTableModel();
        tituloOrdenes = new String[]{"Nombre","Precio", "Categoria"};
        //Agregamos el titulo a la tabla ordenes
        ordenesModel.setColumnIdentifiers(tituloOrdenes);
        tblOrdenes.setModel(ordenesModel);
    }
    
    public void transparenciaBtn()
    {
        //Transparencia a los botones
        btnCocina.setBackground(new Color(255,255,255));
        btnInicio.setBackground(new Color(255,255,255));        
    }
        
    public void eliminarBordeBtn()
    {
        btnMenu.setFocusPainted(false);
        btnCocina.setFocusPainted(false);
        btnInicio.setFocusPainted(false);
        btnSalir.setFocusPainted(false);
        btnCancelar.setFocusPainted(false);
        btnAgregar.setFocusPainted(false);
        btnOrdenar.setFocusPainted(false);
        btnEliminar.setFocusPainted(false);
        btnOrdenarProducto.setFocusPainted(false);
        
    }
    
    //Recibimos la informacion desde Agregar Menu
    public void mostrarProductosTabla() 
    {
        //limpiamos la tabla
        menuModel.setRowCount(0);
        
        //Agregar los productos al modelo
        for (Producto producto : listaProductos) {
            Object[] fila = new Object[3];
            fila[0] = producto.getNombre();
            fila[1] = producto.getPrecio();
            fila[2] = producto.getCategoria();
            menuModel.addRow(fila);
        }
        
        //Establecer el modelo en la tabla
        tblMenu.setModel(menuModel);
    }
    
    //Recibimos la informacion desde Agregar Menu
    public void mostrarOrdenesTabla() 
    {
        //limpiamos la tabla
        ordenesModel.setRowCount(0);
        
        //Agregar los productos al modelo
        for (Orden orden : listaOrdenActual) {
            Object[] fila = new Object[3];
            fila[0] = orden.getNombre();
            fila[1] = orden.getPrecio();
            fila[2] = orden.getCategoria();
            ordenesModel.addRow(fila);
        }
        
        //Establecer el modelo en la tabla
        tblOrdenes.setModel(ordenesModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_gray = new javax.swing.JPanel();
        bg_nav_white = new javax.swing.JPanel();
        tittle_dr = new javax.swing.JLabel();
        btnCocina = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        bg_list_form = new javax.swing.JPanel();
        lblMenu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        lblPrueba = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JFormattedTextField();
        comboCategoria = new javax.swing.JComboBox<>();
        lblCategorias = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnOrdenarProducto = new javax.swing.JButton();
        bg_order = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrdenes = new javax.swing.JTable();
        comboMesa = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        lblPrecioTotal = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_gray.setBackground(new java.awt.Color(235, 234, 234));
        bg_gray.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_nav_white.setBackground(new java.awt.Color(255, 255, 255));
        bg_nav_white.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tittle_dr.setFont(new java.awt.Font("Montserrat Medium", 1, 14)); // NOI18N
        tittle_dr.setText("DR");
        bg_nav_white.add(tittle_dr, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 30, 30));

        btnCocina.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnCocina.setForeground(new java.awt.Color(132, 132, 132));
        btnCocina.setText("COCINA");
        btnCocina.setAlignmentY(0.0F);
        btnCocina.setBorder(null);
        btnCocina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCocinaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCocinaMouseExited(evt);
            }
        });
        btnCocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocinaActionPerformed(evt);
            }
        });
        bg_nav_white.add(btnCocina, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 103, 70, 50));

        btnInicio.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(132, 132, 132));
        btnInicio.setText("INICIO");
        btnInicio.setBorder(null);
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInicioMouseExited(evt);
            }
        });
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        bg_nav_white.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 153, 70, 50));

        btnMenu.setBackground(new java.awt.Color(104, 159, 56));
        btnMenu.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setText("MENU");
        btnMenu.setBorder(null);
        bg_nav_white.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 53, 70, 50));

        btnSalir.setBackground(new java.awt.Color(211, 47, 47));
        btnSalir.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.setBorder(null);
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        bg_nav_white.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 70, 50));

        bg_gray.add(bg_nav_white, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 537));

        bg_list_form.setBackground(new java.awt.Color(255, 255, 255));
        bg_list_form.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenu.setFont(new java.awt.Font("Montserrat Medium", 1, 14)); // NOI18N
        lblMenu.setText("Menu");
        bg_list_form.add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 35));

        tblMenu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tblMenu.setForeground(new java.awt.Color(51, 51, 51));
        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMenu.setGridColor(new java.awt.Color(255, 255, 255));
        tblMenu.setRowHeight(40);
        tblMenu.setRowSelectionAllowed(false);
        tblMenu.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tblMenu.setShowGrid(true);
        tblMenu.setShowHorizontalLines(true);
        tblMenu.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tblMenu);

        bg_list_form.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 107, 490, 418));

        btnAgregar.setBackground(new java.awt.Color(66, 165, 245));
        btnAgregar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("AGREGAR");
        btnAgregar.setBorder(null);
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarMouseExited(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        bg_list_form.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 10, 94, 30));
        bg_list_form.add(lblPrueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 6, -1, -1));
        lblPrueba.getAccessibleContext().setAccessibleParent(lblPrueba);

        lblNombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblNombre.setText("Nombre");
        bg_list_form.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 47, -1, -1));
        bg_list_form.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 68, 160, 33));

        lblPrecio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblPrecio.setText("Precio");
        bg_list_form.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        txtPrecio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        bg_list_form.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 68, 160, 33));

        comboCategoria.setBackground(new java.awt.Color(204, 204, 204));
        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entradas", "Plato Fuerte", "Postre", "Bebidas", "Otro", " " }));
        bg_list_form.add(comboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 67, 160, 35));

        lblCategorias.setText("Categorias");
        bg_list_form.add(lblCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 50, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(211, 47, 47));
        btnEliminar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELEMINIAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        bg_list_form.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 100, 30));

        btnOrdenarProducto.setBackground(new java.awt.Color(104, 159, 56));
        btnOrdenarProducto.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnOrdenarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnOrdenarProducto.setText("ORDENAR");
        btnOrdenarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarProductoActionPerformed(evt);
            }
        });
        bg_list_form.add(btnOrdenarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 10, 100, 30));

        bg_gray.add(bg_list_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 0, 502, 540));

        bg_order.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Montserrat Medium", 1, 14)); // NOI18N
        jLabel1.setText("Orden");

        tblOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblOrdenes);

        comboMesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setText("Numero de Mesa");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Total");

        lblPrecioTotal.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblPrecioTotal.setForeground(new java.awt.Color(102, 102, 102));
        lblPrecioTotal.setText("$");

        javax.swing.GroupLayout bg_orderLayout = new javax.swing.GroupLayout(bg_order);
        bg_order.setLayout(bg_orderLayout);
        bg_orderLayout.setHorizontalGroup(
            bg_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_orderLayout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(104, 104, 104))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_orderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bg_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(comboMesa, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bg_orderLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bg_orderLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        bg_orderLayout.setVerticalGroup(
            bg_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_orderLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bg_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblPrecioTotal))
                .addContainerGap())
        );

        bg_gray.add(bg_order, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 0, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(211, 47, 47));
        btnCancelar.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(null);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        bg_gray.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 483, 107, 49));

        btnOrdenar.setBackground(new java.awt.Color(104, 159, 56));
        btnOrdenar.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        btnOrdenar.setForeground(new java.awt.Color(255, 255, 255));
        btnOrdenar.setText("ORDENAR");
        btnOrdenar.setBorder(null);
        btnOrdenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOrdenarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOrdenarMouseExited(evt);
            }
        });
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });
        bg_gray.add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 483, 157, 49));

        getContentPane().add(bg_gray, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCocinaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCocinaMouseEntered
        btnCocina.setBackground(new Color(215,215,215));
    }//GEN-LAST:event_btnCocinaMouseEntered

    private void btnCocinaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCocinaMouseExited
        btnCocina.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnCocinaMouseExited

    private void btnInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseEntered
        btnInicio.setBackground(new Color(215,215,215));
    }//GEN-LAST:event_btnInicioMouseEntered

    private void btnInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseExited
        btnInicio.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnInicioMouseExited

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        btnSalir.setBackground(new Color(200,46,46));
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        btnSalir.setBackground(new Color(211,47,47));
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocinaActionPerformed
         //ocultamos ventana Inicio
        setVisible(false);
        //costramos ventana Mesero
        new Cocina().setVisible(true);
    }//GEN-LAST:event_btnCocinaActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
         //ocultamos ventana Inicio
        setVisible(false);
        //costramos ventana Mesero
        new Inicio().setVisible(true);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        btnCancelar.setBackground(new Color(200,44,44));
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        btnCancelar.setBackground(new Color(211,47,47));
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnOrdenarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrdenarMouseEntered
        btnOrdenar.setBackground(new Color(83,131,42));
    }//GEN-LAST:event_btnOrdenarMouseEntered

    private void btnOrdenarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrdenarMouseExited
        btnOrdenar.setBackground(new Color(104,159,56));
    }//GEN-LAST:event_btnOrdenarMouseExited

    private void btnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseEntered
        btnAgregar.setBackground(new Color(0,141,255));
    }//GEN-LAST:event_btnAgregarMouseEntered

    private void btnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseExited
        btnAgregar.setBackground(new Color(66,165,245));
    }//GEN-LAST:event_btnAgregarMouseExited

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        //declaramos las variables
        String nombreProducto, categoriaProducto;
        double precioProducto;
        
        //obtenemos los datos del formulario
        nombreProducto = txtNombre.getText();
        Object valorPrecio = txtPrecio.getValue();
        precioProducto = (valorPrecio != null) ? ((Number) valorPrecio).doubleValue() : 0.0;
        categoriaProducto = (String) comboCategoria.getSelectedItem();
        
        Producto producto = new Producto(nombreProducto, precioProducto, categoriaProducto);
        
        //agrego el nuevo producto al arrayList
        listaProductos.add(producto);
        
        //mostramos los productos del arrayList
        mostrarProductosTabla();
        
        //limpiar formulario
        txtNombre.setText("");
        txtPrecio.setText("");
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        //Fila seleccionada
        int selectedRow = tblMenu.getSelectedRow();
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) tblMenu.getModel();
            model.removeRow(selectedRow);
            listaProductos.remove(selectedRow);
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnOrdenarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarProductoActionPerformed
        //Obtenemos la fila seleccionada
        int fila = tblMenu.getSelectedRow();
        
        if (fila!= -1) 
        {
            //Agregar la informacion al array de ordenes
            Orden ordenActual = new Orden(tblMenu.getValueAt(fila, 0), tblMenu.getValueAt(fila, 1), tblMenu.getValueAt(fila, 2));
            listaOrdenActual.add(ordenActual);
        }

        //actualizo el valor total de la orde
        double acumPrecioTotal = 0;
        //recorro el arrar listaOrdenActual y sumo los precios
        for(Orden orden : listaOrdenActual)
        {
            acumPrecioTotal = acumPrecioTotal + orden.getPrecio();
        }
        
        //mostrar el acumulado en el lbl
        lblPrecioTotal.setText(String.valueOf(acumPrecioTotal));
        
        //Mostramos la informacion del array en la tabla
        mostrarOrdenesTabla();
    }//GEN-LAST:event_btnOrdenarProductoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        //Eliminar la informacion del arrayList listaOrdenActual
        listaOrdenActual.clear();
        
        //limpiar la tabla
        ordenesModel.setRowCount(0);
        tblOrdenes.setModel(ordenesModel);
        
        //limpiar el lbl
        lblPrecioTotal.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        //instancia de cocina y le paso la informacion al metodo recibirArrayOrdenes
        String mesa;
        mesa = (String) comboMesa.getSelectedItem();
        
        Cocina cocina = new Cocina();
        
        cocina.recibirArrayOrdenes(listaOrdenActual, mesa);
                
        cocina.setVisible(true);
    }//GEN-LAST:event_btnOrdenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mesero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_gray;
    private javax.swing.JPanel bg_list_form;
    private javax.swing.JPanel bg_nav_white;
    private javax.swing.JPanel bg_order;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCocina;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnOrdenarProducto;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JComboBox<String> comboMesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCategorias;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecioTotal;
    private javax.swing.JLabel lblPrueba;
    private javax.swing.JTable tblMenu;
    private javax.swing.JTable tblOrdenes;
    private javax.swing.JLabel tittle_dr;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JFormattedTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
